### ISSUE TITLE
Add basic Collision Detection for upper and lower bounds

### ISSUE THREAD

**Issue by WheeledParasite** [WheeledParasite/Hack-N-Slash#7] opened 2021-09-25 18:41 UTC
## Summary
We need a way to prevent player & enemies from going off the "bounds" of the play area.  Specifically, the upper and lower bounds.

### Details

- Some method of keeping the player and enemies "in-bounds" must be implemented.
- This could involve using colliders at the top & bottom of the screen.
- But, it could also be a code based solution, that just checks the Y coordinates of player/enemies and doesn't allow it to exceed certain values.

**Comment by gururise** [comment] 2021-09-28 16:44
I can offer some help. Has the code been checked into its own branch yet?

**Comment by WheeledParasite** [comment] 2021-09-28 19:25
Possible to set the bounds in the [Move()](https://github.com/WheeledParasite/Hack-N-Slash/blob/main/Assets/Scripts/PlayerMovement.cs#L67-L92) function of the player movement script. Do you have any code that you have pushed to your own branch that we could look at in order to help?

**Comment by gururise** [comment] 2021-09-28 20:23
@Kuroboshi500 @WheeledParasite 
I forked the repo into my own and made a commit that adds vertical bounds. Could you guys take a look at this [commit](https://github.com/gururise/Hack-N-Slash/commit/76fa7a783eb1a2a3bbd3a2a751f9b27593d65449)?

You can download the code and try it.  I think this might be one way of doing it.

**Comment by Kuroboshi500** [comment] 2021-10-01 21:45
I'm currently testing out the new playerMovement script you've written, just been having issues with getting the inputs to function with the script. I should be able to get back to you soon.

**Comment by Kuroboshi500** [comment] 2021-10-01 22:13
@gururise I got the chance to get the modified PlayerMovement script to function and it does work really well. The only problem with it currently is that if you push the green portion of the arm on the top or bottom of the player, it will propel them in that direction until the green portion is no longer touching the player.

Currently working on see how that can be fixed

**Comment by gururise** [comment] 2021-10-01 22:24
> @gururise I got the chance to get the modified PlayerMovement script to function and it does work really well. The only problem with it currently is that if you push the green portion of the arm on the top or bottom of the player, it will propel them in that direction until the green portion is no longer touching the player.
> 
> Currently working on see how that can be fixed

@Kuroboshi500 glad the script is working!  The issue that you are describing with the arm propelling the player is a separate bug that is unrelated to the movement script.  I think its being cause by the limits being slightly off on the two hinge joints.  I wouldn't worry about that bug for now, @WheeledParasite (or someone else) could add that as a separate issue so that someone who has time can track down exactly what the problem is a fix it.

If the script is working for you, feel free to make whatever adjustments you want to it and then push your changes to your branch that you created... Then after you are satisfied that it works, let @WheeledParasite know so he can merge your branch with the main branch.

**Comment by gururise** [comment] 2021-10-02 17:39
@Kuroboshi500 @WheeledParasite 

Turns out @WheeledParasite was correct, and the player movement bug (issue #34) was primarily due to not ignoring the weapon collider.  I've updated that issue with this additional information.

**Closed** 2021-10-05 01:12 UTC
Labels: enhancement, help wanted, question
